---
- name: Deploy Coolstore Microservices Demo
  hosts: all
  gather_facts: false
  run_once: true
  
    

  tasks:
    - import_tasks: "{{ ANSIBLE_REPO_PATH | default('.') }}/configs/{{env_type}}/create_oc_config.yml"

    - include_role:
        name: "openshift_commons_facts"

    - import_role:
        name: "openshift_coolstore"
      vars:
        project_annotations: "demo=demo-msa-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        enable_cicd: false

    # verify deployed successfully
    - include_tasks: verify_all.yml
      tags: verify
