---
- name: Undeploy Coolstore Microservices Demo
  hosts: all
  gather_facts: false
  run_once: true
  
    
  tasks:
  - import_tasks: "{{ ANSIBLE_REPO_PATH | default('.') }}/configs/{{env_type}}/create_oc_config.yml"

  - include_role:
      name: "openshift_commons_facts"
    vars:
      set_hostname_suffix: false
      
  - name: delete ci/cd projects
    shell: "{{ openshift_cli }} delete project {{ project_cicd }} {{ project_prod }} {{ project_stage }} {{ project_test }} {{ project_dev }}"
    ignore_errors: true

  - name: delete default project
    shell: "{{ openshift_cli }} delete project {{ project_default }}"
    ignore_errors: true
