- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false



  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys

  tasks:
  - debug:
      msg: "Step 000 Pre Infrastructure"

  - name: Generate SSH keys when set_env_authorized_key
    block:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{workdir_dir}}/{{ env_authorized_key }}" -q -N ""
      args:
        creates: "{{workdir_dir}}/{{ env_authorized_key }}"

    - name: fix permission
      file:
        path: "{{workdir_dir}}/{{ env_authorized_key }}"
        mode: 0400

    - name: Generate SSH pub key
      shell: ssh-keygen -y -f "{{workdir_dir}}/{{ env_authorized_key }}" > "{{workdir_dir}}/{{ env_authorized_key }}.pub"
      args:
        creates: "{{workdir_dir}}/{{ env_authorized_key }}.pub"
    when: set_env_authorized_key

- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false



  tags:
    - flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"

- import_playbook: "{{workdir_dir}}/linklight/provisioner/provision_lab.yml"
  tags:
   - linklight_provision

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false



  tags:
  - post_flight_check
  tasks:

  - name: generate email content for user
    block:

      - name: generate user info string for email when a workshop, create_login_page set to true, S3 bucket
        debug:
          msg: "user.info: The list of VMs for this workshop is available at:"

      - name: generate S3 bucket URL for user email when ec2_region is us-east-1
        debug:
          msg:  "user.info: https://s3.amazonaws.com/{{ guid }}.{{ workshop_dns_zone }}/{{ guid }}-index.html"
        when: ec2_region == 'us-east-1'

      - name: generate S3 bucket URL for user email when ec2_region is NOT us-east-1
        debug:
          msg:  "user.info: https://s3-{{ ec2_region }}.amazonaws.com/{{ guid }}.{{ workshop_dns_zone }}/{{ guid }}-index.html"
        when: ec2_region != 'us-east-1'

    when: create_login_page

  - debug:
      msg: "Post-Software checks completed successfully"
