- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

    
    
  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{workdir_dir}}/{{env_authorized_key}}" -q -N ""
      args:
        creates: "{{workdir_dir}}/{{env_authorized_key}}"
      when: set_env_authorized_key

    - name: fix permission
      file:
        path: "{{workdir_dir}}/{{env_authorized_key}}"
        mode: 0400
      when: set_env_authorized_key

    - name: Generate SSH pub key
      shell: ssh-keygen -y -f "{{workdir_dir}}/{{env_authorized_key}}" > "{{workdir_dir}}/{{env_authorized_key}}.pub"
      args:
        creates: "{{workdir_dir}}/{{env_authorized_key}}.pub"
      when: set_env_authorized_key
