- name: Step 00xxxxx post software
  hosts: support
  gather_facts: False
  become: yes
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: Configure windows AD on first windows machine
  hosts:
    - windows[0]
  gather_facts: False
  tags:
    - step004
    - common_tasks
    - windows_tasks
  roles:
    - { role: "windows-ad", when: hostvars.localhost.install_win_ad | bool }
  tasks:
    - name: Reboot upon promotion
      win_reboot:
      when: hostvars.localhost.install_win_ad | bool

    - name: Wait for connection
      wait_for_connection:
      when: hostvars.localhost.install_win_ad | bool

- name: Step lab post software deployment
  hosts: bastions
  gather_facts: False
  become: yes
  tags:
    - opentlc_bastion_tasks
  tasks:
    - import_role:
        name: bastion-opentlc-ipa
      when: install_ipa_client|bool
    - import_role:
        name: ansible-version-lock

    - name: Copy Tower License File
      copy:
        src: "{{secret_dir}}/ans-tower-lab_license.txt"
        dest: /root/license.txt

    - name: Copy Openstack PEM key
      copy:
        src: "{{secret_dir}}/ans-tower-lab_openstack.pem"
        dest: /root/.ssh/openstack.pem
        owner: root
        group: root
        mode: 0400
    - name: Copy Openstack PEM key
      copy:
        src: "{{secret_dir}}/ans-tower-lab_openstack.pub"
        dest: /root/.ssh/openstack.pub
        owner: root
        group: root
        mode: 0400

- name: Post Tower configs
  hosts: towers[0]
  become: yes
  roles:
    - { role: "tower_demo", when: hostvars.localhost.deploy_tower_demo | d(false) | bool }

- name: Install Tower For Homework
  hosts: bastions
  become: yes
  roles:
    - { role: "install-tower", when: hostvars.localhost.deploy_tower_homework | d(false) | bool }

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
