- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  become: no

    
    

- import_playbook: "{{workdir_dir}}/linklight-foundations/provisioner/teardown_lab.yml"
