---

- name: Check if template exists for the environment
  stat:
    path: "../configs/{{ env_type }}/files/cloud_providers/{{cloud_provider}}_cloud_template.j2"
  register: stat_local_template


### This is an ugly workaround for the REPO_DIR_PATH removal process, in future, locate_template should possisbly be moved out of the role and into the config.
### Adde "../" before config name
- name: Use CloudFormation template from the environment
  set_fact:
    cloudformation_template_src: "../configs/{{ env_type }}/files/cloud_providers/{{cloud_provider}}_cloud_template.j2"
  when: stat_local_template.stat.exists

- name: Use the default CloudFormation template
  set_fact:
    cloudformation_template_src: "templates/cloud_template.j2"
  when: not stat_local_template.stat.exists

- name: Print cloudformation_template_src
  debug:
    var: cloudformation_template_src


- debug:
    var: cloudformation_template_src
