- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

    
    
  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys

  tasks:
  - debug:
      msg: "Step 000 Pre Infrastructure"

  - name: Generate SSH keys when set_env_authorized_key 
    block:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{workdir_dir}}/{{ env_authorized_key }}" -q -N ""
      args:
        creates: "{{workdir_dir}}/{{ env_authorized_key }}"

    - name: fix permission
      file:
        path: "{{workdir_dir}}/{{ env_authorized_key }}"
        mode: 0400

    - name: Generate SSH pub key
      shell: ssh-keygen -y -f "{{workdir_dir}}/{{ env_authorized_key }}" > "{{workdir_dir}}/{{ env_authorized_key }}.pub"
      args:
        creates: "{{workdir_dir}}/{{ env_authorized_key }}.pub"
    when: set_env_authorized_key

    # tested version on 2018-07-24 fc86de92080165b72906a1477e389cf0298bd499
    # - name: Clone Ansible linklight repo locally - specfic commit
    #git:
    #  repo: https://github.com/network-automation/linklight.git
    #  dest: "{{workdir_dir}}/linklight"
    #  version: fc86de92080165b72906a1477e389cf0298bd499

- import_playbook: "{{workdir_dir}}/linklight-engine/provisioner/provision_lab.yml"
  tags: 
   - linklight_provision
